server:
        port: 8080
spring:
        datasource:
                url: jdbc:mysql://localhost:3306/flight_booking?createDatabaseIfNotExist=true # &useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
                username: root
                password:
                driver-class-name: com.mysql.cj.jdbc.Driver
        jpa:
                show-sql: true
                generate-ddl: true

                hibernate:
                        ddl-auto: update


                properties:
                        hibernate:
                                jdbc:
                                        useUnicode: true
                                        character_encoding: UTF-8
                                        connection:
                                                characterEncoding: UTF-8
                                connection:
                                        CharSet: UTF-8
                                        useUnicode: true
                                dialect: org.hibernate.dialect.MySQLDialect
                        format_sql: true

                database-platform: org.hibernate.dialect.MySQLDialect
        flyway:
                locations:
                baseline-on-migrate: true
